// Generated by CoffeeScript 1.9.1
(function() {
  var Handler, MongrelRequest, events, zeromq,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  events = require('events');

  zeromq = require('zmq');

  MongrelRequest = require('./mongrel_request').MongrelRequest;

  Handler = (function(superClass) {
    extend(Handler, superClass);

    function Handler(options) {
      this.pullSocket = zeromq.createSocket('pull');
      this.pullSocket.on('message', (function(_this) {
        return function(message) {
          return _this.emit('request', new MongrelRequest(message));
        };
      })(this));
      this.pubSocket = zeromq.createSocket('pub');
      this.pullSocket.connect(options.recv_spec);
      this.pubSocket.connect(options.send_spec);
    }

    Handler.prototype.sendResponse = function(request, response) {
      var header, outBuffer;
      header = [request.uuid, ' ', request.connectionId.length, ':', request.connectionId, ', '].join('');
      outBuffer = new Buffer(header.length + response.length);
      outBuffer.write(header, 'ascii');
      response.copy(outBuffer, header.length);
      return this.pubSocket.send(outBuffer);
    };

    return Handler;

  })(events.EventEmitter);

  exports.Handler = Handler;

}).call(this);
